generate:
	oapi-codegen -package message -generate types docs/User.v1.yaml > message/user.gen.go
	oapi-codegen -package message -generate types docs/MedicalPoint.v1.yaml > message/medical_point.gen.go
