// Package api provides primitives to interact the openapi HTTP API.
//
// Code generated by sios.tech/indigo/oapi-codegen DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"fmt"
	"github.com/deepmap/oapi-codegen/pkg/runtime"
	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi"
	"net/http"
	"strings"
)

// Error defines model for Error.
type Error struct {

	// Error code
	Code int32 `json:"code" validate:"required"`

	// Error message
	Message string `json:"message" validate:"required"`
}

// NewPet defines model for NewPet.
type NewPet struct {

	// Name of the pet
	Name string `json:"name" validate:"required,fhirString,max=1048576"`
	Size int    `json:"size" validate:"required,min=0,max=20"`

	// Type of the pet
	Tag *string `json:"tag,omitempty" validate:"min=2,max=32,regex=^[A-Za-z]+"`
}

// Pet defines model for Pet.
type Pet struct {
	// Embedded struct due to allOf(#/components/schemas/NewPet)
	NewPet
	// Embedded fields due to inline allOf schema

	// Unique id of the pet
	Id int64 `json:"id" validate:"required,min=1,max=100"`
}

// FindPetsParams defines parameters for FindPets.
type FindPetsParams struct {

	// tags to filter by
	Tags *[]string `json:"tags,omitempty"`

	// maximum number of results to return
	Limit *int32 `json:"limit,omitempty"`
}

// AddPetJSONBody defines parameters for AddPet.
type AddPetJSONBody NewPet

// AddPetRequestBody defines body for AddPet for application/json ContentType.
type AddPetJSONRequestBody AddPetJSONBody

type ServerInterface interface {
	// Returns all pets (GET /pets)
	FindPets(w http.ResponseWriter, r *http.Request)
	// Creates a new pet (POST /pets)
	AddPet(w http.ResponseWriter, r *http.Request)
	// Deletes a pet by ID (DELETE /pets/{id})
	DeletePet(w http.ResponseWriter, r *http.Request)
	// Returns a pet by ID (GET /pets/{id})
	FindPetById(w http.ResponseWriter, r *http.Request)
}

// ParamsForFindPets operation parameters from context
func ParamsForFindPets(ctx context.Context) *FindPetsParams {
	return ctx.Value("FindPetsParams").(*FindPetsParams)
}

// FindPets operation middleware
func FindPetsCtx(next http.Handler) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		ctx := r.Context()

		var err error

		// Parameter object where we will unmarshal all parameters from the context
		var params FindPetsParams

		// ------------- Optional query parameter "tags" -------------
		if paramValue := r.URL.Query().Get("tags"); paramValue != "" {

		}

		err = runtime.BindQueryParameter("form", true, false, "tags", r.URL.Query(), &params.Tags)
		if err != nil {
			http.Error(w, fmt.Sprintf("Invalid format for parameter tags: %s", err), http.StatusBadRequest)
			return
		}

		// ------------- Optional query parameter "limit" -------------
		if paramValue := r.URL.Query().Get("limit"); paramValue != "" {

		}

		err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
		if err != nil {
			http.Error(w, fmt.Sprintf("Invalid format for parameter limit: %s", err), http.StatusBadRequest)
			return
		}

		ctx = context.WithValue(ctx, "FindPetsParams", &params)

		next.ServeHTTP(w, r.WithContext(ctx))
	})
}

// AddPet operation middleware
func AddPetCtx(next http.Handler) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		ctx := r.Context()

		next.ServeHTTP(w, r.WithContext(ctx))
	})
}

// DeletePet operation middleware
func DeletePetCtx(next http.Handler) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		ctx := r.Context()

		var err error

		// ------------- Path parameter "id" -------------
		var id int64

		err = runtime.BindStyledParameter("simple", false, "id", chi.URLParam(r, "id"), &id)
		if err != nil {
			http.Error(w, fmt.Sprintf("Invalid format for parameter id: %s", err), http.StatusBadRequest)
			return
		}

		ctx = context.WithValue(ctx, "id", id)

		next.ServeHTTP(w, r.WithContext(ctx))
	})
}

// FindPetById operation middleware
func FindPetByIdCtx(next http.Handler) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		ctx := r.Context()

		var err error

		// ------------- Path parameter "id" -------------
		var id int64

		err = runtime.BindStyledParameter("simple", false, "id", chi.URLParam(r, "id"), &id)
		if err != nil {
			http.Error(w, fmt.Sprintf("Invalid format for parameter id: %s", err), http.StatusBadRequest)
			return
		}

		ctx = context.WithValue(ctx, "id", id)

		next.ServeHTTP(w, r.WithContext(ctx))
	})
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerFromMux(si, chi.NewRouter())
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	r.Group(func(r chi.Router) {
		r.Use(FindPetsCtx)
		r.Get("/pets", si.FindPets)
	})
	r.Group(func(r chi.Router) {
		r.Use(AddPetCtx)
		r.Post("/pets", si.AddPet)
	})
	r.Group(func(r chi.Router) {
		r.Use(DeletePetCtx)
		r.Delete("/pets/{id}", si.DeletePet)
	})
	r.Group(func(r chi.Router) {
		r.Use(FindPetByIdCtx)
		r.Get("/pets/{id}", si.FindPetById)
	})

	return r
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+RX224byRH9lUInbxkNadnZBAQCRGt5AQK7thLt5iG2ApR6imQZfRl3V1PiCvz3oHqG",
	"N0m2s0gQJNgXksPpy6lTp6pPPxgbfR8DBclm9mCyXZHH+vNNSjHpjz7FnpIw1b9t7Ei/O8o2cS8cg5kN",
	"g6G+a8wiJo9iZoaDvDw3jZFNT8MjLSmZbWM85YzLzy60e72fmiVxWJrttjGJPhVO1JnZezNuuBt+s23M",
	"W7q7InmKO6B/Zru36AniAmRF0JM82bAx92fLeGZLlujPBJe662LF6Xr33uP9n15MX/3x93/4pu6f+ee6",
	"j8d79sWb2fm0MZ7D8DB9joy67GNkP276R8g83n9PYSkrM3t5XtfcPZ43pkcRSjrxH+8vzv6OZz/f/O6r",
	"9FVORsg3+8Hx9iNZUWAjkejcu4WZvX8wv020MDPzm8lBNZNRMpOR+G3zmHnunkb3U+BPhYC70xCPlfPN",
	"qyHmgbgX02MaXzyl8VFo3D0T0c1Wh3FYxEHJQdDWCMkjOzMz2LMQ+j/nO1wuKbUcTTMqx1wP/8HF1Rx+",
	"JPSmMSXppJVIP5tMjuZsm0fhXkBG3zuqk2WFAiVTBtSws8REgBkwAN0PwyRCRz6GLAmFYEEoJVEGDpWs",
	"dz0FXellO4Xck+UFW6xbNcaxpZDpIHlz0aNdEZy30xPIeTaZ3N3dtVhftzEtJ+PcPPl+/vrN2+s3Z+ft",
	"tF2Jd1WllHx+t7imtGZLz8U9qUMmKjsWd8zZ1RimacyaUh5IedFO26muHHsK2LOZmZf1r6rmVdXORAnS",
	"H8tBiqe0/pWkpJABnatMwiJFXxnKmyzkB6r1uWRKsFKSraWcQeKH8BY9ZOrAxtCxpyDFA2Vp4QckSwEz",
	"CPk+Jsi4ZBHOkLFnCg0EspBWMdiSIZM/GsAC6ElauKBAGAAFlgnX3CFgWRZqAC0w2uK4Tm3hdUl4y1IS",
	"xI4juJjINxBTwERASxIgRyO6QLYBW1IuWUvHkZWSW7gsnMEzSEk95wb64tYcMOlelKIG3YBwsNyVILDG",
	"xCXDR+1pLcwDrNDCSkFgzgS9QyGEjq0Ur3TMhxLTWLDjnrPlsAQMotEcYne8LA73kfcrTCQJdyTqePDR",
	"URYmYN9T6liZ+huv0Q8BoeNPBT10jMpMwgyfNLY1ORYIMYDEJDEpJbyg0O13b+EqIWUKojApsD8AKCkg",
	"rKMr0qPAmgIFVMADufrhsSRdYx4OKy8ojawv0LLjfLJJ3UE/mkN+LeTYoSNNbNcoj5YSigam3y1cl9xT",
	"6FhZdqji6aKLqVEFZrKiaq5RVqlo1A2sacW2OARtdKkrHhzfUoot/BDTLQMVzj52x2nQ11XYDi0HxvZD",
	"+BCuqauZKBkWpOJz8TamOoHiQTGpSCq+Ba0Nj3XBkXzOrgEqJ9UypBxcUR2qOlu4WmEm54bC6CmN0yvN",
	"Nb0ksMBi+bYMhONuHx13PH9NbkwdryklbE631joB7pp9IQa+XbXwk0BPzlEQynrC9DEX0kraFVELSgXu",
	"qkCLbsflbqVdWJXJpgLZyyKUYEESZ6kH2JoFqYXvSrYEJLUbdIX3VaCdIltylLjCGfS7m+BVLQWreGzx",
	"GQN4XGrI5MZstfCXMkz10WnehuxRGbRzgNLsmw9gsVokw8hRnkPYozjGJrOvRhWLJhg4NAcoY+EGzrwD",
	"nBWDZSkdK9ScEYrsdDYmctjphLS6XwtXx4mpzI0Y+0TCxR91rkE0pTnSt7be9oMecWou6nE378zMfMeh",
	"0/OlHhtJCaCUq1s5PSwEl9r3YcFOKMHtxqgVMDPzqVDaHM55HaemqNqa6l+EfD2DHpmpvb3AlHCjz1k2",
	"9dhTG1ON0CmC0cxAKP6WkjqfRLk4qbBSPcs+g8mxZzkB9VWPvb1RQ5R7bS0V/fl0unM9FAZf1/duNA6T",
	"j1khPjwX9pdM3+D4HhGxfeJ/ehLYgRnc0QKLk1+E50swhrvKMxuXQPe9tlbtwcOYxuTiPabNMwZCsfUx",
	"P2M1XidCqZYt0J2O3Xmx6mv0DB6w6xC1c87FO+qeiPWiU62awatSlm9jt/mPsbBz4E9puCJRjWHX6dce",
	"tjn2zJIKbf9NzXxVKv8/0niS8Pq++tHJA3fbQSKO5Jlb5fC/zs0clq7ebuAWtc3GQTXzS8hFY3pGI5d1",
	"9iCTL3a0+aX2kH7I7Yhl7B9qoA/tg7snmf5cL6m3rn+hl7x6GrUCGVB0/0uJvNwno2ZhA/NLhfflC8Vp",
	"xvZ5nF9+7vj5djPvflG+FiR29V9L16+2jB9ldMh+HUJpvUvTyT1+dyVvjy62ejvd3mz/GQAA///cBtl2",
	"LhMAAA==",
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file.
func GetSwagger() (*openapi3.Swagger, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %s", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}

	swagger, err := openapi3.NewSwaggerLoader().LoadSwaggerFromData(buf.Bytes())
	if err != nil {
		return nil, fmt.Errorf("error loading Swagger: %s", err)
	}
	return swagger, nil
}
