// Package message provides primitives to interact the openapi HTTP API.
//
// Code generated by sios.tech/indigo/oapi-codegen DO NOT EDIT.
package message

import (
	openapi_types "github.com/deepmap/oapi-codegen/pkg/types"
)

// MedicalPoint defines model for MedicalPoint.
type MedicalPoint struct {
	AnnouncementDate openapi_types.Date `json:"announcementDate"`
	Category         *string            `json:"category,omitempty"`
	EffectiveDate    openapi_types.Date `json:"effectiveDate"`
	Id               string             `json:"id"`
	Name             *string            `json:"name,omitempty"`
	Point            int                `json:"point" validate:"min=1,max=10"`
	PracticeCode     *string            `json:"practiceCode,omitempty"`
	Segment          string             `json:"segment"`
}

