// Package message provides primitives to interact the openapi HTTP API.
//
// Code generated by sios.tech/indigo/oapi-codegen DO NOT EDIT.
package message

import (
	openapi_types "sios.tech/indigo/oapi-codegen/pkg/types"
)

// MedicalPoint defines model for MedicalPoint.
type MedicalPoint struct {
	AnnouncementDate openapi_types.Date `json:"announcementDate" validate:"required"`
	Category         *string            `json:"category,omitempty"`
	EffectiveDate    openapi_types.Date `json:"effectiveDate" validate:"required"`
	Id               string             `json:"id" validate:"required"`
	Name             *string            `json:"name,omitempty"`
	Point            int                `json:"point" validate:"required,min=1,max=10"`
	PracticeCode     *string            `json:"practiceCode,omitempty"`
	Segment          string             `json:"segment" validate:"required"`
}
